### ISSUE TITLE
THE LIFEBRINGER VAULT DOESNT HAVE TINY FANS UNDER THE EXTERNAL AIRLOCKS

### ISSUE THREAD

**Issue by triplezeta** [WaspStation/WaspStation-1.0#139]
## Round ID:
368

## Reproduction:
1. be lifebringer
2. open external airlock
3. get sick from miasma and or slowly die because of BZ

**Comment by Epsilos** [comment]
Not only that, it doesn't even have a scrubber to try and take care of whatever makes it in.
