### ISSUE TITLE
[BUG] Suit sensors detecting SSD comatose patients as dead

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#141]
## Round ID:
[378](https://scrubby.melonmesa.com/round/378)

## Testmerges:
SSD sleeping

## Reproduction:
on binary suit sensors, when going SSD and falling asleep, suit sensors report the SSD person as dead

**Comment by Epsilos** [comment]
Wrong! This man is deceased.
