### ISSUE TITLE
chemical synthesizers are borked

### ISSUE THREAD

**Issue by triplezeta** [WaspStation/WaspStation-1.0#142]
## Round ID:
[394](https://scrubby.melonmesa.com/round/394)

## Reproduction:
wrench down chemical synthesizer, set it up and everything. You may notice that upon changing the synthesizer's settings, it will immediately change orientation to face south. 
Okay, whatever, so you lay some duct down and- it's not connecting. 
Chemical synthesizers will not connect to fluid ducts, essentially making them useless.

**Comment by Superyodeler** [comment]
Wierd, I remember them working yesterday

**Comment by triplezeta** [comment]
the server just got updated

**Comment by Superyodeler** [comment]
I was finally able to test this, and while the synthesizers were kinda glitchy, I didn't have the same problem and was able to set up a simple factory. Not sure if this got fixed or if it was just quality code from tg.

**Comment by triplezeta** [comment]
okay, the ACTUAL reason why the synthesizers aren't working isn't because they aren't working, it's because somebody messed up their directional states. Go figure.
