### ISSUE TITLE
inconsistent anesthesia

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#166]
## Round ID:

400 and 505

## Testmerges:

unknown

## Reproduction:

when you're put under gas anasthetics (the white and red striped nitrous oxide tank), it's really inconsistent on when you'll wake up

sometimes you'll get woken up like normal and other times you'll be unconscious for upwards of five minutes no matter how much someone tries to shake you up

this is even more horrendous with the heavy sleeper trait, with instances of this de facto comatose state lasting over 15 minutes

all in all it's even less of a roleplay incentive to use anesthetics if you're the kind of person to even use them to begin with

**Comment by MarkSuckerberg** [comment]
Is this still an issue?

**Comment by MarkSuckerberg** [comment]
Doesn't seem to have come up again, assuming it's fixed.
