### ISSUE TITLE
is there still any reason as to why you cant change your suit sensors

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#203]
## Round ID:

probably the beginning of time

## Testmerges:

i donno

## Reproduction:

try changing your suit sensors
![Screenshot (569)](https://user-images.githubusercontent.com/58999300/81757664-7481c400-9474-11ea-9811-f506c2ace14a.png)

**Comment by Superyodeler** [comment]
I'm able to change my suit sensors, this might be an envirosuit thing

**Comment by dinnerwoerror** [comment]
WoRkS oN mY mAcHiNe

**Comment by Superyodeler** [comment]
BrEaKs On My MaChInE
