### ISSUE TITLE
Hey guys I figured out the box powernet issue!

### ISSUE THREAD

**Issue by triplezeta** [WaspStation/WaspStation-1.0#229]
## Round ID:
Round 675, map Kilostation
## Testmerges:

not relevant

## Reproduction:

1. move the mining shuttle from the station to lavaland
2. move the mining shuttle from lavaland to the station

Okay, so I THINK this is what's causing the problem. Since box is special, and has an APC on the mining shuttle, the powernet suddenly having to support the shuttle APC causes the whole thing to break! Since Kilo also has box's mining shuttle, it shares this problem. Updating the powernet by cutting one of the wires under an SMES and rewiring it fixes the entire thing.

**Comment by triplezeta** [comment]
Additionally, sending the shuttle down to lavaland suddenly causes the entire powernet to work again. Go figure.

**Comment by Superyodeler** [comment]
Wew, good work.

**Comment by Maldaris** [comment]
Resolved
