### ISSUE TITLE
Can't rod smite on Centcomm Z level

### ISSUE THREAD

**Issue by Superyodeler** [WaspStation/WaspStation-1.0#298]
## Testmerges:

247
273

## Reproduction:

Cannot rod smite on Centcomm Z level

Reported by @AsciiSquid

**Comment by Maldaris** [comment]
Can confirm that @dee-dubya managed to rod me in centcomm on round 1099.

Closing.

**Comment by dee-dubya** [comment]
I'm an engineer, that means I solve practical problems.
