### ISSUE TITLE
[FEATURE] Magboot Modularity/Sandal Compatability for Digitigrade Feet

### ISSUE THREAD

**Issue by Maldaris** [WaspStation/WaspStation-1.0#321]
## Name of feature:

Digitigrade Shoes

### Related Pull Request on other codebase:

N/A

### Additional Info:

Essentially giving the ability for Digitigrade feet to fit in mag-boots and sandals. With mag-boots, a screwdriver used on them converts them to digitigrade mode, only wearable by races with those leg types. Sandals can just be used as is.

**Comment by triplezeta** [comment]
i still hate the idea of digitigrade magboots outside of some sort of ghetto conversion method but it's not that big of a deal

**Comment by Maldaris** [comment]
So describe the problem in more detail because I'm not familiar with it from a spriting side.

**Comment by triplezeta** [comment]
its less spriting side and more internalized autistic hate of adding dedicated features to make life easier for digitigrade feet users

**Comment by dinnerwoerror** [comment]
gUhHh, I'm LiZaR, i CaNt HaVe NoRmAl FeEt, CaN I PlEaSe Be AcCoMoDaTeD bY tHe GlOrIoUs StAtE?

No.
