### ISSUE TITLE
[BUG] Drone issues

### ISSUE THREAD

**Issue by SynnGraffkin** [WaspStation/WaspStation-1.0#330]
Issue reported from  Round ID: 1160 (BoomerStation - MRP)

Reporting client version: 513.1513

Selecting a drone prompts null. 
![image](https://user-images.githubusercontent.com/6519623/86993441-03a81100-c172-11ea-95f1-bc5873b1e78b.png)

Drones have two of three laws

![image](https://user-images.githubusercontent.com/6519623/86993459-115d9680-c172-11ea-8356-35e6fab8be30.png)

**Comment by ADepressedPyroshark** [comment]
Time to interfere with everyone

**Comment by untrius** [comment]
I can't seem to replicate the two-of-three-laws bug anymore.  Has it been fixed?

**Comment by MarkSuckerberg** [comment]
I'm pretty sure it was either a one-time bug or it's been solved. I'll close the issue in a bit.

**Comment by untrius** [comment]
Ok.  I've confirmed that the null drone prompt still happens, so I wouldn't close this one quite yet.

**Comment by MarkSuckerberg** [comment]
Oh, noted
