### ISSUE TITLE
Can't make regen jelly

### ISSUE THREAD

**Issue by ADepressedPyroshark** [WaspStation/WaspStation-1.0#459]
Issue reported from  Round ID: [1616](https://scrubby.melonmesa.com/round/1616) (BoomerStation - MRP)

Reporting client version: 513.1528

Basically, The chemical recipe for regen jelly (1u omnzine and slime jelly) doesn't work and can't be made
I'm unshure if this is a bug since the wiki doesn't have the recipe but I don't remember any pr saying you can't make it anymore so i'm putting this here just incase

**Comment by SynnGraffkin** [comment]
If the wiki says Omnizine, that's a wiki error. 

```c
/datum/chemical_reaction/regen_jelly
	results = list(/datum/reagent/medicine/regen_jelly = 2)
	required_reagents = list(/datum/reagent/medicine/tricordrazine = 1, /datum/reagent/toxin/slimejelly = 1)
```
