### ISSUE TITLE
Station Engineers with no funny alt titles are spawning with the Electrician outfit

### ISSUE THREAD

**Issue by tiramisuapimancer** [WaspStation/WaspStation-1.0#462]
Issue reported from  Round ID: [1625](https://scrubby.melonmesa.com/round/1625) (BoomerStation - MRP)

Reporting client version: 513.1526

Shows up in character creator, even, and you will genuinely spawn with this- happened to both me and someone else. 
![image](https://user-images.githubusercontent.com/32314478/93651074-bf7c8c80-f9bc-11ea-87f0-bd4c3336c3e2.png)

**Comment by MarkSuckerberg** [comment]
Will look into it tonight
