### ISSUE TITLE
[BUG] AI Private Channel Radio Token :o Not Working

### ISSUE THREAD

**Issue by untrius** [WaspStation/WaspStation-1.0#466]
## Testmerges: None
Happens on live and local.  Local has no testmerges.

## Details:
Using :o as the AI or via a headset with access to it, does not send a message to the AI Private channel.  The AI Private Channel can be spoken to and listened to via intercoms and station bounced radios.  I've confirmed that both a radio headset with a sec borg encryption key and the AI with intercoms off can hear the AI Private channel.

## Reproduction:
1. Play as AI
2. Attempt to send a message starting with :o
3. Message will not be seen by sender, recorded by tcomms servers, or heard by players listening to 144.7.

or

1. Put /obj/item/encryptionkey/secbot into a radio headset
2. Send a message with :s to confirm the headset and encryption key work
3. Attempt to send a message starting with :o
4. Message will not be seen by sender, recorded by tcomms servers, or heard by players listening to 144.7.

**Comment by Shadowtail117** [comment]
Could reproduce. Oddly enough this does bypass the entire rest of the `say` code. No feedback is sent even to the user, whereas a nonexistent or incorrect channel key would at least put the message in chat.

**Comment by untrius** [comment]
I appear to have found the issue:

![image](https://user-images.githubusercontent.com/7697956/94997477-021f9680-0571-11eb-994e-a4ee55547794.png)

**Comment by Maldaris** [comment]
Fixed in #506
