### ISSUE TITLE
why the hell are pyroclastic anomalies so devastating

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#523]
## Round ID:

pretty much every pyroclastic anomaly that's gone un-neutralized since monstermos

## Testmerges:

n/a

## Reproduction:

un-neutralized pyroclastic anomalies are literally baby stars

![Screenshot (945)](https://user-images.githubusercontent.com/58999300/96355413-4abd7080-1096-11eb-81e9-9c3e02e0d8b4.png)

that's 20,000 degrees kelvin

for reference, that's about 3 and a half times the temperature at the surface of the fucking sun

something tells me that this is not how things are meant to be

**Comment by Maldaris** [comment]
They've been nerfed in terms of output and tick-rate. The answer is don't ignore them.

**Comment by triplezeta** [comment]
even before the- oh ok
