### ISSUE TITLE
[BUG] Spelling mistake in Cargo Vault Space Ruin

### ISSUE THREAD

**Issue by Maldaris** [WaspStation/WaspStation-1.0#552]
## Reproduction:

![image](https://user-images.githubusercontent.com/1953773/99136443-cefe0780-25f2-11eb-9aaf-7370ee2983a6.png)

**Comment by kiVts** [comment]
No one did this yet?

**Comment by Maldaris** [comment]
@kiVts Not that I'm aware of.

**Comment by Jack7D1** [comment]
Woh! I didn't see this. I'll put out a PR with a bunch of spelling and grammar fixes whenever uni allows.
I've got a big list of things that need fixing
