### ISSUE TITLE
[BUG] Borg cookie synthesizer doesn't dispense cookies

### ISSUE THREAD

**Issue by SynnGraffkin** [WaspStation/WaspStation-1.0#554]
## Round ID:

[1883](https://scrubby.melonmesa.com/round/1883)

## Testmerges:

#540
#544 

## Reproduction:

Become Peacekeeper borg, attempt to dispense cookies, no cookies dispensed

**Comment by Maldaris** [comment]
Cease all further development until this is fixed 🔨 🔫

**Comment by Jack7D1** [comment]
var/cooldown = 0
	///The period between recharges
:thinking:

**Comment by Jack7D1** [comment]
Cookie sythesizer dispenses cookies

**Comment by triplezeta** [comment]
oh ok
