### ISSUE TITLE
[BUG] Unable to scavenge batteries from mechs

### ISSUE THREAD

**Issue by SynnGraffkin** [WaspStation/WaspStation-1.0#555]
## Round ID:

[1883](https://scrubby.melonmesa.com/round/1883)

## Testmerges:

#540
#544 

## Reproduction:

Attempted to retrieve a battery from a functional Ripley in the space ruin, followed the instructions on the wiki but hands or screwdriver wasn't able to pull out a battery after opening the panel in maintenance mode.

**Comment by SynnGraffkin** [comment]
This extends to mechs that are created by players as well. Couldn't do shit on a mech after making one in round 1929

**Comment by MarkSuckerberg** [comment]
![image](https://user-images.githubusercontent.com/29362068/100407334-c44d6480-302d-11eb-9310-930d581982c1.png)
![image](https://user-images.githubusercontent.com/29362068/100407352-cca59f80-302d-11eb-86b3-f271d5374afe.png)
