### ISSUE TITLE
[BUG] Actions in game preferences locks up the world thread

### ISSUE THREAD

**Issue by Jack7D1** [WaspStation/WaspStation-1.0#558]
Likely caused by the lack of a connected SQL server prompting the server to halt until it receives a response that won't come.
During this halt time the thread uses very little system resources.

## Reproduction: 
Fire up a local server and just click game preferences in the setup menu.

**Comment by Maldaris** [comment]
The fix for this is to comment out `SQL_ENABLED` in your local server's config.

**Comment by Jack7D1** [comment]
hfshfshfdhshdfgsfhdgsfdsh thanks
