### ISSUE TITLE
kilo mapping fuckies megathread

### ISSUE THREAD

**Issue by triplezeta** [WaspStation/WaspStation-1.0#560]
put your spotted mapping issues with kilostation here below in the comments so that i can fix them later

## Testmerges:

https://github.com/WaspStation/WaspStation-1.0/pull/548

**Comment by triplezeta** [comment]
issue #1: fax machines are entirely absent from all of kilo

**Comment by dinnerwoerror** [comment]
hmm, yes, a long continuous engineering hallway and bar/library with no firelocks or airlocks to break it up, 1 vent, 1 scrubber, perfect for an entire engineering/service department

**Comment by triplezeta** [comment]
vault unwired roundstart
theres an intercomm set to the AI private channel in front of the bar

**Comment by untrius** [comment]
The heater for the mixed air supply before distro, is facing the wrong way.
![image](https://user-images.githubusercontent.com/7697956/99860776-aed1c980-2b59-11eb-87a6-9a22221d1b2c.png)

**Comment by untrius** [comment]
The airlock in atmos is missing a distro pipe, so the airlock doesn't work.
![image](https://user-images.githubusercontent.com/7697956/99860957-49caa380-2b5a-11eb-8549-c9f934c5d6b7.png)

**Comment by untrius** [comment]
I also find it strange that some airlocks have air alarms in them, given that they'll create atmos alarms when the airlock is cycled to the outside.

**Comment by untrius** [comment]
I can't tell if this is intentional.  I could see it going either way, really.
![image](https://user-images.githubusercontent.com/7697956/99861652-5c45dc80-2b5c-11eb-9ed9-9e5f8d89366b.png)

**Comment by triplezeta** [comment]
that was something from the original kilo, and frankly I don't know why it was there in the first place. If enough people complain about it I will rectify this.

**Comment by Maldaris** [comment]
More work to do at the outset of the shift isn't necessarily a bad thing 👀

**Comment by untrius** [comment]
I've seen carp spawn inside a couple times.  Again, not sure if intentional.
![image](https://user-images.githubusercontent.com/7697956/99862876-26efbd80-2b61-11eb-84b8-f153f582d5f2.png)

**Comment by triplezeta** [comment]
absolutely not intentional what the

**Comment by untrius** [comment]
There was a shark in the emitter room too.

**Comment by TheNeoGamer42** [comment]
kilo has no synthflesh roundstart

**Comment by untrius** [comment]
Kilo may be missing a jukebox

**Comment by untrius** [comment]
This row on the NE solars is missing wires under them.
![image](https://user-images.githubusercontent.com/7697956/100288089-8f60e500-2f3b-11eb-8d80-d2e37ebb602d.png)

**Comment by untrius** [comment]
Airlock SE of engineering has an air alarm.
![image](https://user-images.githubusercontent.com/7697956/100288248-e6ff5080-2f3b-11eb-965c-26c7f6f3e1c9.png)

**Comment by untrius** [comment]
There's a rock pile blocking an airlock in maint by the grav gen
![image](https://user-images.githubusercontent.com/7697956/100367200-7e5db580-2fc7-11eb-9dd2-6e191ad7b845.png)

**Comment by untrius** [comment]
Camera facing the wrong direction in emitter room
![image](https://user-images.githubusercontent.com/7697956/100461205-14f4aa00-308e-11eb-9335-816c4ae20575.png)

**Comment by triplezeta** [comment]
closing this, leave kilo mapping fuckies in actual issues now
