### ISSUE TITLE
Emotes no work

### ISSUE THREAD

**Issue by theboy6545** [WaspStation/WaspStation-1.0#595]
Issue reported from  Round ID: 1979 (BoomerStation - RP)

Reporting client version: 513.1535

When I try a *spin or a *speen, I just say it, and I don't do the action

**Comment by MarkSuckerberg** [comment]
Caused by #593, should be fixed on round restart.

**Comment by Jack7D1** [comment]
aaaa close issue

**Comment by MarkSuckerberg** [comment]
aeiou
