### ISSUE TITLE
roundstart prisoners spawn in the arrivals shuttle instead of in the permabrig

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#66]
## Round ID:
i think maybe round 27

## Reproduction:
spawn in as a roundstart prisoner (at least a plasmaman one) and you'll spawn with the normal prisoner shit, but on the arrivals shuttle instead of the actual permabrig, which is where i'm pretty sure they should be spawning

**Comment by MarkSuckerberg** [comment]
I cried a little when I read this

**Comment by dinnerwoerror** [comment]
oh yea it was on pubby station

**Comment by MarkSuckerberg** [comment]
fixed via speedpush

**Comment by dinnerwoerror** [comment]
are you sure about that

**Comment by MarkSuckerberg** [comment]
I blame tg
