### ISSUE TITLE
the medical-security radio headset & encryption key are invisible

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#76]
## Round ID:
68
## Testmerges:
brig physician
## Reproduction:
dude literally just look

![Screenshot (434)](https://user-images.githubusercontent.com/58999300/75653644-da4f0580-5c12-11ea-9531-7bb5b44c5c77.png)

**Comment by MarkSuckerberg** [comment]
fixed by 9c9e215
