### ISSUE TITLE
unintended consequences of pull request 56

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#91]
## Round ID:

n/a

## Testmerges:

https://github.com/WaspStation/WaspStation-1.0/pull/56

## Reproduction:

whenever someone does any kind of emote, it adds a period punctuation sign at the end, and this is any emote, which means that there are awkward emotes with 2 periods at the end, and whenever someone does the flip or speen or really any emote or whatever, it just says "big dick rick ."

i'm sure there's more instances, but i suspect you get my drift

**Comment by MarkSuckerberg** [comment]
I need to check into this
