### ISSUE TITLE
you can make a freezer so efficient that you can achieve a state of temperature only possible prior to the big bang

### ISSUE THREAD

**Issue by dinnerwoerror** [WaspStation/WaspStation-1.0#94]
## Round ID:
129
## Testmerges:

something regarding TGUI

## Reproduction:
if you click on the freezer TGUI at the right place, you can have a temperature below absolute zero

![Screenshot (452)](https://user-images.githubusercontent.com/58999300/76382502-2fc39a80-6316-11ea-85c0-be30c271269c.png)

**Comment by triplezeta** [comment]
k

**Comment by dinnerwoerror** [comment]
k

**Comment by dinnerwoerror** [comment]
the fun part is that this glitch actually works, cryo had a temperature of 0 degrees kelvin

**Comment by MarkSuckerberg** [comment]
this literally destroys the gas because the volume is multiplied by the temperature IIRC. thankies teegee

**Comment by Maldaris** [comment]
Fixed locally & Resolved
